### PR TITLE
Added Chinese Translations for v0.2.1

### PR DESCRIPTION
**Pull request by noahziheng**
I'm a VATPRC S3 TMA controller.Request add my translation of Chinese Simpifed.I create it by XML ".ts" file.Source is English.And I'll write a topic in forum.vatprc.net.I'll obey GPLv3 to write github URL.Thanks a lot.Let's hope for good cooperation between us.

### CODE REVIEW

**Comment by noahziheng** [comment]
In fact,I'm hard to use transifex due to Chinese GFW.

**Comment by garrappachc** [comment]
Thank you for the support. v0.2.1 is no longer maintained nor supported, as v1.0 is on the way. Normally the bot automatically pulls translations from Transifex and pushes new strings, so it's easy to keep up with all the changes. But if you say GFW is an issue for you using Transifex, I'll let you know when all strings are frozen, so you can translate v1.0 once, without need for further changes, alright?

**Comment by noahziheng** [comment]
Thanks for answer.I'll try my best to login transifex,actually,it's a great tools.And,when the v1.0 release?
In fact,I'm good at web,I can't compile the code in develop by cmake.So I'm looking foraward to v1.0 released news.

**Comment by garrappachc** [comment]
I expect v1.0 to be somewhere around the beginning of 2016 - stil couple of features to be implemented, some bugs to be squashed.
I'll make an annoucement on Trasifex when Vatsinator gets its first beta version.

**Comment by noahziheng** [comment]
All right.Actually,I finished Chinese_Simpifed translation in transifex yesterday.Thanks a lot.Looking farword to beta version,now the pull request will close.

**Comment by garrappachc** [comment]
Thank you for the Transifex translation. I'll enable it after next Transifex merge (which happens every Saturday), so it'll be available in nightly builds.

**Pull request closed without merging**
